# Generated by Django 3.2.18 on 2023-03-09 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ride',
        ),
    ]
