# Generated by Django 3.2.18 on 2023-03-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('logPage', '0007_alter_client_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('emailId', models.EmailField(blank=True, max_length=200)),
                ('passWd', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
