# Generated by Django 3.2.18 on 2023-03-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logPage', '0008_auto_20230309_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
